# Generated by Django 4.2.6 on 2023-10-13 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('form_name', models.CharField(blank=True, max_length=255, null=True)),
                ('form_link', models.CharField(blank=True, max_length=255, null=True)),
                ('form_qrcode', models.TextField(blank=True, null=True)),
                ('attributes', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormName', models.CharField(blank=True, max_length=255, null=True)),
                ('FormValue', models.TextField()),
                ('FormID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.formattributes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
